/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_simonis_NativeWithGC */

#ifndef _Included_org_simonis_NativeWithGC
#define _Included_org_simonis_NativeWithGC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_simonis_NativeWithGC
 * Method:    native_call
 * Signature: ([JJZ)V
 */
JNIEXPORT void JNICALL Java_org_simonis_NativeWithGC_native_1call
  (JNIEnv *, jclass, jlongArray, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
